(stoa0040_stoa050)_onwards
OpenGreekAndLatin/csel-dev pull request #371
Opened 2021-11-23 16:26 UTC by AlisonBabeu

Beginning changes to final batch of files

2021-11-23 18:46 UTC, lcerrato approved these changes

2021-11-23 19:29 UTC, lcerrato requested changes

2021-11-23 19:29 UTC, lcerrato commented on data/stoa0040/stoa053/stoa0040.stoa053.opp-lat1.xml
> +              <biblScope unit="volume">Sectio 6, Pars II</biblScope>
needs language attribute

2021-11-23 19:29 UTC, lcerrato commented on data/stoa0040/stoa077/stoa0040.stoa077.opp-lat1.xml
> +              <biblScope unit="volume" xml:lang="lat">Sectio 1, Pars 2</biblScope>
needs lanaguage attribute

2021-11-23 20:13 UTC, AlisonBabeu commented on data/stoa0040/stoa077/stoa0040.stoa077.opp-lat1.xml
> +              <biblScope unit="volume" xml:lang="lat">Sectio 1, Pars 2</biblScope>
Added language attributes.

2021-11-29 18:03 UTC, lcerrato approved these changes

2021-11-29 18:04 UTC, lcerrato approved these changes

2021-11-29 18:44 UTC, merged