textgroup_standardization
OpenGreekAndLatin/csel-dev pull request #373
Opened 2021-11-29 16:45 UTC by AlisonBabeu

Updated textgroup names to not include dates. Updated pseudo author.

2021-11-30 20:03 UTC, lcerrato requested changes

2021-11-30 20:03 UTC, lcerrato commented on data/stoa0104c/__cts__.xml
> +  <ti:groupname xml:lang="eng">Cyprianus Gallus</ti:groupname>
attribute Latin

2021-11-30 20:03 UTC, lcerrato commented on data/stoa0224b/__cts__.xml
> +  <ti:groupname xml:lang="lat">Paulinus Petricordiae</ti:groupname>
Latin attribute

2021-11-30 20:03 UTC, lcerrato commented on data/stoa0292d/__cts__.xml
> +  <ti:groupname xml:lang="eng">Victor Vitensis</ti:groupname>
attribute Latin?

2021-12-01 14:15 UTC, AlisonBabeu commented on data/stoa0089a/__cts__.xml
> +  <ti:groupname xml:lang="eng">Claudianus Mamertus</ti:groupname>
Ok, I've done that and will make the other changes and resubmit.

2021-12-07 20:09 UTC, merged